version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:80"
    # volumes:
    #   - .:/var/www/html
    networks:
      - smart-trolley-network

networks:
  smart-trolley-network:
    external: true
